FROM openjdk:17-alpine 
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
COPY  web-app-embedded/target/web-app-embedded-0.0.1-SNAPSHOT.jar web-app-embedded.jar
EXPOSE 8080
ENTRYPOINT exec java $JAVA_OPTS -jar web-app-embedded.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
#ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar cnwork.jar
